CREATE TABLE DARCA ( 
id_darca NUMBER(22) NOT NULL,
meno VARCHAR(40) NOT NULL,
vek NUMBER(22) NOT NULL,
krvna_skupina VARCHAR(3) NOT NULL,
choroby VARCHAR(255) NOT NULL,
pohlavie VARCHAR(4),
adresa VARCHAR(80),
telefonne_cislo VARCHAR(20));

CREATE TABLE PACIENT ( 
id_pacient NUMBER(22) NOT NULL,
meno VARCHAR(40) NOT NULL,
vek NUMBER(22) NOT NULL,
krvna_skupina VARCHAR(3) NOT NULL,
choroby VARCHAR(255) NOT NULL,
pohlavie VARCHAR(4),
adresa VARCHAR(80),
telefonne_cislo VARCHAR(20));

CREATE TABLE KRV ( 
id_krv NUMBER(22) NOT NULL,
krvna_skupina VARCHAR(3) NOT NULL,
objem NUMBER(22) NOT NULL);

CREATE TABLE PERSONAL ( 
id_personal NUMBER(22) NOT NULL,
meno VARCHAR(40) NOT NULL,
vek NUMBER(22),
adresa VARCHAR(80),
telefonne_cislo VARCHAR(20),
pohlavie VARCHAR(4));

CREATE TABLE BANKA ( 
adresa VARCHAR(80) NOT NULL,
telefonne_cislo VARCHAR(20));

ALTER TABLE DARCA ADD CONSTRAINT PK_Darca PRIMARY KEY (id_darca);
ALTER TABLE PACIENT ADD CONSTRAINT PK_Pacient PRIMARY KEY (id_pacient);
ALTER TABLE KRV ADD CONSTRAINT PK_Krv PRIMARY KEY (id_krv);
ALTER TABLE PERSONAL ADD CONSTRAINT PK_Personal PRIMARY KEY (id_personal);
ALTER TABLE KRV ADD CONSTRAINT FK_Krv_Darca
FOREIGN KEY (id_darca) REFERENCES DARCA (id_darca);
ALTER TABLE KRV ADD CONSTRAINT FK_Krv_Pacient
FOREIGN KEY (id_pacient) REFERENCES PACIENT (id_pacient);
ALTER TABLE PERSONAL ADD CONSTRAINT FK_Personal_Darca
FOREIGN KEY (id_darca) REFERENCES DARCA (id_darca);
ALTER TABLE PERSONAL ADD CONSTRAINT FK_Personal_Pacient
FOREIGN KEY (id_pacient) REFERENCES PACIENT (id_pacient);
ALTER TABLE BANKA ADD CONSTRAINT FK_Banka_Personal
FOREIGN KEY (id_personal) REFERENCES PERSONAL (id_personal);
ALTER TABLE BANKA ADD CONSTRAINT FK_Banka_Darca
FOREIGN KEY (id_darca) REFERENCES DARCA (id_darca);
ALTER TABLE BANKA ADD CONSTRAINT FK_Banka_Pacient
FOREIGN KEY (id_pacient) REFERENCES PACIENT (id_pacient);